packages:
  - afs/*
  - packages/*
  - models/*
  - memory/*
  - examples/*
  - tests/*
  - observability/*
  - docs-examples
  - blocklets/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@vscode/ripgrep'
  - '@zowe/secrets-for-zowe-sdk'
  - core-js
  - core-js-pure
  - esbuild
  - fast-folder-size
  - protobufjs
  - simple-git-hooks
  - sqlite3
